name: newgeneration
favicon: null
layout_spectrum: 0.014408171409741044
typography_spectrum: 0.3768817444797605
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6743528959341347
  lightness: 0.44641727255657315
  saturation: 0.45865776180289686
  rhythmicContrast: 0.011835443321615458
purpose: []
